// eslint-disable-next-line import/no-anonymous-default-export
export default [
    {
        img: "livro6.png",
        title: "As cicatrizes do poder",
        text: `
        
        <h1>As cicatrizes do poder</h1>
        <h2>O Caos de Yiridessa</h2>
        <br/>
        <p>
            &emsp;&emsp;<span class="first-letter">N</span>o vasto cenário de Yiridessa, somos transportados para um mundo pós-apocalíptico, onde as cicatrizes da guerra pelo poder se tornaram profundas fissuras nas relações entre as raças. Uma disputa feroz pelos territórios transformou cada centímetro do mapa em um campo de batalha, onde o controle significava a formação de exércitos imponentes que almejavam dominar o que agora chamamos de mundo. O anseio insaciável pelo poder, que permeava cada recanto, transcendia até mesmo os limites celestiais, ecoando entre os deuses ancestrais, que assistiam impotentes ao lento declínio do planeta Terra. À medida que os dias avançavam, a situação deteriorava-se, mergulhando a vida em um abismo. Pais, em um ato desesperado, sacrificavam seus próprios filhos por um mero pedaço de carne, enquanto maridos, cegados por promessas vazias de poder, entregavam suas esposas ao caos.<br/>
            &emsp;&emsp;Foi nesse contexto caótico que até mesmo os demônios mais perversos conhecidos por suas práticas canibais e apetites vorazes por outros demônios, insensíveis e sem preocupações, encontravam-se desesperados, ávidos por um aumento de poder que pudesse alterar o curso dos acontecimentos a seu favor.<br/>
            &emsp;&emsp;Existe uma escassez significativa de informações sobre os deuses ancestrais - e quando menciono escassez, refiro-me a uma fração tão ínfima que até mesmo os mais antigos dentre nós são incapazes de mensurar a extensão de sua existência, suas origens ou o propósito subjacente à criação do universo. É verdadeiramente notável como algo de tamanha magnitude pode permanecer tão envolto em mistério. Os deuses ancestrais são entidades divinas e celestiais, cujo significado exato permanece elusivo; alguns os concebem como a própria essência da vida, enquanto outros os enxergam como a personificação do vazio primordial. A única certeza que temos é a existência de quatro dessas criaturas, embora jamais tenham sido avistadas por olhos mortais. Acredita-se que essas entidades divinas perambulem pelo infinito, dando origem a mundos em um ciclo interminável, onde a criação é seguida pela devastação causada pelos próprios habitantes do mundo.<br/>
            &emsp;&emsp;Vestígios dispersos de informações sobre essas criaturas celestiais existem, porém, distinguir a verdade da ficção é uma empreitada verdadeiramente hercúlea, especialmente em um universo tão vasto quanto Yiridessa, onde charlatães proliferam. Os deuses ancestrais são dotados de onisciência, onipotência e onipresença, mas o que desejam que todos reconheçam é seu propósito primordial: a criação de mundos ao longo do infinito, durante sua jornada. Essa jornada segue um ciclo familiar: inicia-se com a criação do mundo, enquanto os ancestrais deixam sua marca na coordenada inicial, seguida pelo desenvolvimento do mundo enquanto transitam para o próximo ponto de criação, até culminar no fim do mundo, indicado pelos vestígios deixados para trás pelos ancestrais, que facilitarão o término daquela existência.<br/>
            &emsp;&emsp;Os deuses menores são estritamente proibidos de mencionar os ancestrais, sob pena de perderem suas vidas. Tal proibição sugere que os deuses ancestrais possuem uma magnitude de poder muito além do que se imagina superficialmente. - Leroye Armstrong, primeiro elfo ancião de Aetherya.<br/><br/>
        </p>
        <br/>
        <p>
            "Na profecia, o começo se revela através de flores impregnadas pelo doce aroma de canela,
            O riso de uma criança ressoa, ecoando nos recônditos de cada coração;
            Pétalas rosa dos girassóis pintam o "O Legado dos Deuses Ancestrais" de uma vida por nascer.
            O princípio se entrelaça à compaixão entre pares,
            Empatia envolve cada ser no continente, despertando sensibilidade;
            O sabor adocicado de frutas sazonais e o desejo de compartilhá-las florescem.
            O início se concretiza no primeiro sorriso do inverno, tingido com lágrimas."
        </p>
        <br/><br/><br/>

        `
    },
    {
        img: "livro2.png",
        title: "Fragmentos do Infinito",
        text: `
          
        <h1>Fragmentos do Infinito</h1>
        <h2>O Caos e os Ancestrais</h2>

        <p>&emsp;&emsp;<span class="first-letter">V</span>ocê já se deparou com relatos apocalípticos, histórias que proclamam o fim do mundo? Muitos as consideram falsas, meras fábulas destinadas a instilar o medo nos mais jovens. Se você optar por não acreditar, compreendo; não estou aqui para persuadi-lo. Tudo o que fizemos, cada ação que empreendemos, teve um único propósito: preservar a sua espécie de alguma maneira. É crucial compreender que tudo, absolutamente tudo, segue um ciclo. Os deuses, esses seres divinos que moldam nosso destino, fazem questão de nos recordar desse ciclo sempre que anseiam por nossa morte. Não são benevolentes; são egoístas, ávidos por clamor e adoração, pois é dessa reverência que extraem sua vitalidade. O mundo jamais findará, pois eles jamais permitirão que a fonte de sua energia se esgote. Contudo, atente-se ao ditado "Deus castiga", o mais verdadeiro dos aforismos. No instante em que sua devoção não for mais suficiente ou quando sua alma estiver comprometida, nada, absolutamente nada, o protegerá da ira divina. Seja prudente e siga a dança sugerida pelos deuses, ou arrisque perder algo vital, algo que jamais poderá ser recuperado. Talvez você nunca tenha refletido profundamente sobre isso; afinal, não é uma contemplação para qualquer mente.</p>

        <p>&emsp;&emsp;A narrativa do ciclo que conhecemos melhor, o da vida, permeia nossa existência, não é verdade? Nascemos, crescemos, desenvolvemos nossas jornadas, envelhecemos – seja com glória ou não – e, por fim, partimos. Este é um Ciclo. Todas as vicissitudes que ocorrem nesse intervalo não interrompem o ciclo; elas simplesmente são partes intrínsecas dele.</p>

        <p>&emsp;&emsp;Alguns se entregam a teorias e depositam fé no destino, acreditando que cada passo já está predestinado desde o nascimento. O que esquecem de compartilhar é que somos meras gotas em um vasto oceano chamado destino. O que acontece conosco, com nossos vizinhos ou com nossos interesses românticos não influencia algo ainda maior que se desdobrará para todos nós. Compreender que nossas vidas são um ciclo é vital, mas é imperativo expandir ainda mais nossa mente.</p>

        <p>&emsp;&emsp;Tudo que conhecemos segue um ciclo. Acordar de manhã cedo, se alimentar, trabalhar e, então, retornar ao lar é um ciclo, seja uma rotina ou não. Separar-se de um parceiro romântico e iniciar um novo interesse é um ciclo, seja uma rotina ou não. O ciclo começa, se desenvolve, termina e, em sua maioria, recomeça. Ele NUNCA é interrompido, independentemente do que ocorre no percurso. A morte também se insere nesse ciclo; ela pode ser um recomeço, algo que talvez você ainda não tenha compreendido.</p>

        <p> &emsp;&emsp;Você percebe o que está acontecendo? Está confuso e precisa compreender as coisas abruptamente, e talvez tudo que estou compartilhando pareça fazer menos sentido do que esperava (ISSO É UM CICLO). Você talvez pense que estou louco, que estou delirando ou, no mínimo, tentando vender uma possível salvação para você neste mundo (ISSO FAZ PARTE DO CICLO, MESMO QUE PARA MIM SEJA UMA ROTINA). Nascer e morrer, percebeu que isso NÃO altera em nada o ciclo do universo em que vivemos? Nunca havia percebido, não é? Quanta arrogância. Exatamente, somos pequenos demais para compreender tudo isso.</p>

        <blockquote>“Na profecia, o término se revela com o desmatamento das florestas impregnadas pelo cheiro de enxofre; <br>
        Os lamentos torturantes ecoam, provocados por presas e garras afiadas; <br>
        Cada criatura derrama sangue sem um propósito claro, extinguindo suas vidas.<br>
        O fim se insinua na falta de propósito em continuar a lutar por aqueles que ainda subsistem;<br>
        Na apatia para auxiliar o próximo com gestos simples e descomplicados;<br>
        Nos corações amargos daqueles que esqueceram como amar seus semelhantes - e até mesmo outros;<br>
        O término se manifesta no sofrimento e na ausência de vitalidade. Necessitamos iniciar o ciclo novamente.”</blockquote>

        <p>&emsp;&emsp;<span class="first-letter">E</span>stou aqui para partilhar contigo alguns conceitos. Agora que tens a essência do ciclo em mente, podemos ir além dessa "loucura" que compartilho. Antes de revelar o restante, é crucial compreendermos o que representam as trevas. Talvez já tenhas lido antigas narrativas em papiros sobre criaturas sanguessugas, seres caóticos corrompidos pelas litanias de suas raças, ou criaturas pouco pensantes ávidas apenas por se alimentar. Contudo, devo confessar um segredo: NADA disso realmente caracteriza as trevas. É verdade que não são criaturas benevolentes, amigáveis, que gostaríamos de ter em nosso convívio, mas a verdadeira ameaça que enfrentamos ultrapassa essas imagens. As trevas almejam muito mais do que simples atos caóticos. Elas não se importam nem consigo mesmas. Pode estar a questionar-se sobre o que exatamente desejam. Recordas-te de eu mencionei que nenhum ciclo pode ser interrompido? Pois bem, é isso que as trevas procuram: impedir que o fim encontre um novo começo, interromper o ciclo em sua jornada. Talvez agora me vejas como contraditório. "Disseste que nenhum ciclo pode ser interrompido...", e é exatamente isso. Nenhum ciclo pode ser interrompido, e estou aqui há muito tempo assegurando que assim seja. Sozinhas, as trevas não têm o poder de interromper o ciclo, mas as lendas da criadora maior indicam uma única alma que pode. A cada ciclo de nossa espécie, o sopro da vida nasce em uma pequena criatura capaz de destruir isso, mas as lendas não mencionam seu aparecimento.</p>

        <p>&emsp;&emsp;As narrativas em papiros dos mais antigos descreviam os recomeços, embora fossem confusas e difíceis de acreditar. A esperança, contudo, persistia. As almas desapareciam com o primeiro sopro, mas os espólios permaneciam. Após milênios, o continente estava repovoado. Você percebe o ciclo recomeçando? O tempo passou, e os desafios retornaram. A harmonia entre criaturas era frágil, a amizade nem sempre prevalecia. No entanto, nada disso alterava nosso ciclo. O destino do universo estava novamente ameaçado pelas trevas, que corrompiam o solo de Yiridessa. As criaturas das trevas tomaram o controle, e eu, esgotado, tentei recomeçar, mas minha força se dissipou, e como poeira ao vento, deixei o continente contra minha vontade. Eu me perguntava por onde estavam os celestiais, por que construíam e não se preocupavam com a destruição? Os deuses menores, por que não estavam presentes em ajudar?</p>

        <p>&emsp;&emsp;Era uma necessidade, uma tentativa de proteger esta dimensão da extinção iminente. Apesar de meu poder, as trevas persistiam em destruir os ciclos. Minha falha no último recomeço pareceu ser algo fora do ciclo. Os conselheiros da ordem, agora com um propósito restaurado, mantinham o rumo. O destino não era uma fantasia; ele existia. Se você está lendo isso, deve estar se perguntando como protegeremos os ciclos sem os Ancestrais. Minha alma em meu corpo ainda vaga pelo continente, parte essencial do ciclo, do recomeço, aguardando finalmente o momento do meu fim. O mundo que conhecemos mudará sem essa renovação, mas vocês, sem interrupções, podem alterar o ciclo. Se o recomeço falhar, eu não estarei aqui para contar essa história novamente, e ninguém estará vivo para ouvi-la. Depois dos acontecimentos de Aetherya, ninguém ouviu mais falar sobre a ordem espiritual, a ordem dos magos ou as bruxas do coven, caso não realizemos o recomeço do ciclo, a extinção do caos, nunca mais haverá paz até a nossa morte. No momento certo, vocês encontrarão como fazer, e ele os guiará no seu novo recomeço e de nossas espécies.</p>

        <p>&emsp;&emsp;Tudo agora está mais confuso, eu compreendo. Não desistam de ouvir, pois isso é crucial…</p>

        <blockquote>“Na dança eterna do ciclo, o recomeço não simboliza o verdadeiro fim.<br>
        Ao finalizar, emerge a oportunidade de recomeçar;<br>
        A cada volta nesse ciclo contínuo, novos destinos podem entrelaçar-se;<br>
        Em cada caminho recém-trilhado, uma renovação autêntica para tentarmos novamente.<br>
        O ciclo da vida e da morte não são opostos, mas sim elos de uma mesma corrente;<br>
        A luz e as trevas, longe de ciclos distintos, tecem juntas uma única narrativa;<br>
        A criança marcada pelo fim é também parte intrínseca do ciclo, imune à interrupção.”</blockquote>

        <p>- Jhoseval Hurrix, o barqueiro do reino de Al Miraj.</p>
        `
    },
    {
        img: "background_preludio.jpg",
        title: "O Legado dos Deuses Ancestrais",
        text: `
          
        <h2>O Legado dos Deuses Ancestrais</h2>

        <p>
            &emsp;&emsp;<span class="first-letter">T</span>antas vezes me questiono sobre o porquê de permitirmos que tragédias desabem sobre os mortais. Nós, divindades, encontramos certo deleite ao ouvir os lamentos das criaturas, clamando por auxílio, dispostos a oferecer o que não possuem em troca de um suporte que, para nós, seria insignificante. Contudo, é essencial compreender algo: nosso poder divino, toda a nossa força, emanam da fé que os devotos depositam em nossa divindade. Quando somos esquecidos ou negligenciados, nossa potência se dissipa. Curioso, não é? Mesmo que os devotos não percebam, suas celebrações, por vezes simples caprichos culturais, inadvertidamente fortalecem deuses, como na troca de presentes durante um feriado ao final de um ano, por exemplo.<br/>
            &emsp;&emsp;<span class="first-letter">N</span>ão possuímos controle absoluto; não podemos interferir no livre arbítrio dos habitantes - pelo que dizem, tampouco nas escolhas de nossos familiares divinos - também não precisa acreditar nisso. Um singelo ato pode desencadear uma cascata de efeitos, comprometendo nossa energia vital conquistada com tanto esforço por meio das adorações e acarretando consequências no conselho divino. Os deuses ancestrais mesmo não se envolvem, mas nós não somos como eles, a fonte de poder deles é inesgotável, nós precisamos lutar pela nossa.<br/>
            &emsp;&emsp;<span class="first-letter">N</span>o vasto cenário das dimensões divinas, a ordem é frequentemente dividida em dois ou até mesmo três reinos, variando conforme seu tamanho. Cada um desses reinos ostenta suas próprias normas de convivência, grupos distintos, exércitos exclusivos, bênçãos divinas específicas, minérios singulares, culinárias distintivas, enfim, cada fragmento da criação divina exibe sua singularidade. Até mesmo o processo de eleição dos soberanos desses impérios é esculpido pela evolução única de cada um. É comum que desenvolvamos uma afeição por um dos reinos, embora tal predileção seja extremamente subjetiva e passageira. Por vezes, somos mais generosos em nossas oferendas a um determinado reino, ocasionalmente erguemos altares e templos em sua honra - isso nos traz satisfação. Espera-se que o deus que mais se manifesta no reino seja venerado e adorado por seus habitantes, contudo, essa devoção nem sempre se realiza conforme o esperado. Em ocasiões distintas, testemunhamos reinos onde os habitantes optavam por cultuar outros deuses, muitas vezes movidos por imaturidade ou mesmo pela intenção de minar a fé alheia.<br/>
            &emsp;&emsp;<span class="first-letter">A</span>lguns de nós raramente são cultuados, mas encontramos maneiras alternativas de sobreviver. A adoração não se manifesta apenas em orações, oferendas ou rituais. Muitas vezes, ela surge de formas inesperadas, como atitudes que refletem a esfera de atuação de um deus. A deusa do amor, dos prazeres carnais, patrona das coelhos, dos javalis e dos macacos, dos perfumes, também conhecida como deusa das rosas e responsável pela primavera, Milodrye, por exemplo, incita o desejo nas pessoas. Quando ela consegue, sem interferência direta, provocar um profundo amor entre um casal em relações íntimas, quando induz um desejo intenso que desencadeia a desordem em um casamento puramente pelo apetite e vontade sexual, ou até mesmo quando instiga a promoção de uma orgia em uma casa de banho, sua vitalidade se renova, e ela nem precisa participar da atividade para se fortalecer ou ser adorada. Existem relatos em que sua persuasão relacionada aos desejos obscuros a fizeram como um Djinn, capaz de trocar favores, adorações e até mesmo a alma de seus devotos, por pequenos desejos realizados com sua magia do amor.<br/>
            &emsp;&emsp;<span class="first-letter">H</span>á relatos sobre o deus Uitar, patrono dos cavalos, deus da beleza incontestável e do reflexo, deus da auto estima e da graciosidade, deus da luz e do fogo. A adoração a esse deus envolve orações direcionadas para o Sol, simbolizando a luz e a clareza que ele representa. Os seguidores frequentemente oferecem seus bens mais preciosos em sacrifício, queimando-os em lareiras ou fogueiras como um gesto de devoção e purificação. A personalidade do deus é caracterizada por uma rigidez implacável e uma obsessão quase insana pela iluminação e clareza, sempre buscando iluminar o caminho para todos com um fervor inabalável.<br/>
            &emsp;&emsp;<span class="first-letter">K</span>hefos ostentava a titulação de Deus da abundante colheita, da culinária refinada e do paladar requintado, do vinho exímio e das festividades, além de ser o patrono dos bovinos e suínos. Este deus se destacava pela singularidade de sua aparência em relação aos padrões sociais convencionais, e suas oferendas consistiam sempre em alimentos de qualidade e sabor inigualável. Renomado por sua predileção em trocar favores por banquetes sumptuosos, por vezes ocorreram incidentes em que devotos, após o cumprimento das solicitações de Khefos, falharam em ofertar-lhe os devidos festins. Em tais circunstâncias, o deus utilizou todos os bens e riquezas desses fiéis como se fossem iguarias, incluindo, por vezes, seus próprios entes queridos.<br/>
            &emsp;&emsp;<span class="first-letter">N</span>yara é reverenciada como a Deusa dos sonhos, do repouso e do descanso, sendo também conhecido como o mensageiro celestial das nuvens. Ele personifica o conforto e a serenidade, tendo como patronos os coalas, roedores e preguiças, das aves noturnas como a coruja e das aves de penas luxuosas como o ganso, de cisne e pavão. Além disso, está intrinsecamente ligado aos anseios humanos, possuindo a capacidade de discernir os mais profundos desejos por meio dos sonhos que permeiam uma noite de sono tranquila. Permitir que os sonhos se manifestem, mesmo que possam assumir a forma de pesadelos e compartilhá-los com os próximos, tornou-se a forma mais comum de adoração a Nyara. Geralmente, as pessoas reverenciam o deus do sono antes de se deitarem, suplicando por sonhos serenos e pacíficos e como forma de adoração, utilizam as penas aves luxuosas para se deitar e suplicar por boas noites de sono.<br/>
            &emsp;&emsp;<span class="first-letter">H</span>axy é reverenciado como o Deus da beligerância e do conflito, das artes estratégicas de guerra e da aplicação da tortura, sendo o arauto do derramamento de sangue e da aversão. Ele é o padroeiro dos morcegos e dos bodes, personificando a fúria. Suas oferendas exigem usualmente promessas de batalhas e, geralmente, ele não concede atenção àqueles desprovidos de influência no reino. Há uma forte correlação entre Haxy e o Deus do submundo, frequentemente sendo adorados em conjunto. Causar repulsa nas pessoas torna-se uma forma indireta de adoração a este deus.<br/>
            &emsp;&emsp;<span class="first-letter">A</span>latéia é reverenciada como a divindade dos poderosos, um ser venerado por aqueles que exibem um orgulho desmedido por seus feitos. Conhecida também como a deusa lunar, ela personifica o brilho noturno, a obscuridade e o temor, além de ser associada à desonestidade e à vergonha. Desde tempos imemoriais, Alatéia foi vinculada a animais de pelagem escura, como corvos, cervos de pelagem negra, panteras, raposas negras e serpentes. Alatéia não demanda oferendas, apenas presta auxílio àqueles que compartilham de seus princípios de poder. Embora se sugira que possa ter desempenhado um papel na criação do submundo, poucos detalhes sobre essa narrativa perduram. Segundo a tradição, ela reinará sobre os mortos, conferindo poder àqueles que transitarem para seu reino após a morte, onde apenas os indivíduos fortes e poderosos serão considerados dignos de sua atenção.<br/>
            &emsp;&emsp;<span class="first-letter">W</span>hadarr é reconhecido como a divindade do ouro e das riquezas, o patrono dos belos presentes e da honestidade, além de personificação da prosperidade, da saúde e a fortuna. Desde tempos imemoriais, tem sido associada aos felinos, principalmente aos gatos, que o reverenciam como seu protetor, as moedas de ouro e as barras de todos os valores. Sua essência reflete o apego ao material, e as oferendas destinadas a ele devem consistir em objetos tangíveis e de valor substancial. Whadarr é conhecido por seu discernimento aguçado em relação ao valor, avaliando meticulosamente a condição e a essência de seus devotos antes de considerar qualquer oferta como verdadeiramente significativa. Narrativas lendárias destacam que Whadarr uma vez considerou um simples boneco de madeira de uma criança como algo de grande valor, pois representava tudo o que ela possuía, enquanto ignorou um baú repleto de moedas douradas pertencente a um rei, visto como uma insignificância diante da vasta fortuna do monarca. A tradição também conta que Whadarr, embora uma divindade, foi alvo de uma maldição imposta pelos Ancestrais, na qual tudo o que toca se transforma automaticamente em ouro. A natureza exata dessa suposta maldição permanece envolta em mistério, mas o deus da fortuna utiliza habilmente esse dom para seu próprio benefício.<br/>
            &emsp;&emsp;<span class="first-letter">É</span> um tanto complexo, não é mesmo? Mas sempre podem esclarecer suas dúvidas com os bibliotecários de cada reino. Nessas bibliotecas, encontrarão inúmeros livros com todas essas histórias, desvendando a origem de cada criação. No último recomeço, os deuses deram origem a criaturas e reinos, contextualizando sua importância para o ciclo recomeçar.
        </p>
        <p>
            - Página 7, os contos de Milodrye, por Jasper Pridemore, escrivão do reino de Al Miraj.
        </p>
        `
    },
    {
        img: "livro3.png",
        title: "Aetherya",
        text: `
          
        <h1>REINOS</h1>
        <h2>AETHERYA</h2>

        <p>
            &emsp;&emsp;<span class="first-letter">E</span>m um reino de esplendor e pureza imaculada, Aetherya, os Aetherianos carregam consigo o dom da natureza e a bênção das águas. Esta graça divina confere-lhes uma tranquilidade serena e uma aversão a conflitos, o que muitas vezes é mal interpretado por outros povos como covardia. Em Aetherya, a própria natureza, generosa e abundante, dá vida sem a necessidade de pais, permitindo que os Aetherianos nasçam diretamente dos elementos da terra. Com o passar dos anos, a missão de preservar os recursos naturais se tornou uma parte intrínseca de sua identidade, transformando-os em incansáveis guardiões da natureza e de suas criações.<br/>
            &emsp;&emsp;A singularidade da criação dos Aetherianos é notável; seu reino foi o primeiro a erigir estruturas e dar vida a seres sem intervenção direta dos deuses. Suas criaturas eram inteligentes e refletiam a calma da natureza, mas possuíam a bravura do oceano. Contrariando a impressão de covardia, os Aetherianos enfrentaram grandes desafios. No entanto, o caminho não foi fácil.<br/>
            &emsp;&emsp;Os primeiros seres criados em Aetherya foram os elfos, cuja arrogância rivalizava com a própria soberania dos deuses. O continente viu um período de grande sofrimento e busca por perfeição. As diferentes etnias, apesar de possuírem uma essência comum, se tornaram rivais implacáveis. Elfos lunares e elfos solares se detestavam sem razão aparente, disputando o trono de Aetherya com uma violência interminável. As crianças que não demonstravam talentos excepcionais eram relegadas ao trabalho forçado, e as famílias de baixa estirpe enfrentavam uma vida de escravidão e escassez. Contudo, o brilho do pó mágico representava uma esperança para os jovens. Apesar da crueldade daquele tempo, as fadas prometeram que na próxima estação, a tirania não continuaria.<br/>
            &emsp;&emsp;O campo de batalha era um cenário de sangue e destruição. Faunos protetores das florestas eram dilacerados enquanto tentavam defender seus lares; kitsunes e lobos lutavam entre si como se fossem inimigos naturais; descendentes de lagartos se escondiam em busca de sobrevivência. Aqueles que não se aliaram a nenhuma das facções élficas morriam ao lado dos inimigos. O trono já tinha sido manchado com muito sangue, e a herança de Aetherya estava sendo negligenciada, com as criaturas aquáticas vivendo sob uma ditadura cruel e preferindo a escravidão subaquática à devastação da guerra.<br/>
            &emsp;&emsp;Na aurora do primeiro dia da primavera, os elfos celebraram a mudança de estação com um festival repleto de dança e banquetes. Era uma tradição sagrada, pois uma lenda afirmava que a falta do ritual traria mil anos de inverno a Aetherya. No entanto, durante a celebração, as fadas apareceram carregando o corpo de uma fada morta. Os elfos, acostumados a atribuir divindade às fadas por sua graciosidade, estavam prontos para iniciar uma nova disputa. Foi então que a rainha das fadas se levantou e mostrou aos elfos a futilidade de sua guerra. Ela revelou que, enquanto eles se preocupavam com suas disputas internas, outros seres estavam causando mal até mesmo a uma entidade de pura bondade como a fada. Com isso, os elfos compreendendo a lição, selaram a paz entre os elfos solares e lunares, restaurando a harmonia em Aetherya.<br/>
            &emsp;&emsp;Com a paz estabelecida e a monarquia restaurada, os elfos celebraram mais uma vez. Mas, mesmo com a harmonia restaurada, o reino estava longe de estar em completa tranquilidade.<br/>
            &emsp;&emsp;Nas profundezas das águas que margeiam o reino, existia um reino anexo conhecido como Atlanta. Este lugar, de inacessível beleza e mistério, estava sob o domínio de uma tirania cruel. Inicialmente, os sereianos temiam sair de seu reino devido à guerra dos elfos, mas Atlanta era governada com punho de ferro, e seus plebeus viviam em condições desumanas.<br/>
            &emsp;&emsp;Tudo mudou com a fuga desesperada de um tritão escravizado. Ele encontrou refúgio nas margens de Aetherya e procurou asilo com o primeiro rei elfo da nova era. A situação estava tão crítica que os habitantes temiam que cada evento, reunião ou festa fosse marcado por sangue. O rei elfo, mostrando astúcia e sabedoria, elaborou um plano para atrair o tirano de Atlanta à superfície e eliminá-lo, libertando assim o povo subjugado.<br/>
            &emsp;&emsp;Gratos pela liberdade, os habitantes de Atlanta se uniram aos elfos, e Atlanta foi incorporada a Aetherya. Desde então, sereias e tritões têm sido respeitados por suas responsabilidades e desempenhos, habitando lagos, rios e oceanos como guardiões incansáveis das águas e da vida que nelas floresce.<br/><br/>
        </p>

        `
    },
    {
        img: "livro4.png",
        title: "Al-Miraje",
        text: `
          
        <h1>REINOS</h1>
        <h2>AL-MIRAJE</h2>

        <p>
            <strong>Al-Miraje, a Terra das Areias</strong><br/>
            &emsp;&emsp;Nos confins do deserto, onde o sol inclemente queimava as dunas sem fim, ergue-se uma terra envolta em lendas e mistérios: Al-Miraje. Conhecida como a Terra das Areias, esta região era um lugar de desolação e luta, onde o vento carregava canções antigas e as estrelas guardavam segredos dos tempos imemoriais. Para muitos, o deserto representava um desafio insuperável, uma vasta extensão de areia dourada que testava os limites da resistência humana.<br/>
            <br/>
            <strong>Uma Terra de Sofrimento e Medo</strong><br/>
            &emsp;&emsp;O reino em questão era dividido e assolado por desafios incessantes. As tribos nômades, vivendo isoladas, enfrentavam a dura realidade do deserto. A fome e a sede eram inimigas constantes, enquanto o calor implacável do dia drenava a energia dos que se aventuravam além da segurança de suas tendas. As noites, embora mais frescas, traziam consigo um perigo ainda mais aterrorizante.<br/>
            &emsp;&emsp;Criaturas hostis vagavam sob o céu noturno, monstros de pesadelos que atacavam sem aviso, seus olhos brilhando com malícia na escuridão. Esses seres demoníacos eram uma ameaça constante, forçando as tribos a manterem vigílias intermináveis, temendo pelo momento em que a próxima sombra se moveria em direção ao acampamento.<br/>
            <br/>
            <strong>O Fardo da Isolação</strong><br/>
            &emsp;&emsp;A sensação de desolação era intensificada pelo isolamento entre as tribos. A comunicação entre elas era rara, e cada grupo via os outros mais como rivais do que aliados. Essa divisão enfraquecia a todos, e o senso de comunidade era quase inexistente. Muitas vezes, as tribos viam umas às outras com desconfiança, competindo pelos escassos recursos que o deserto oferecia.<br/>
            &emsp;&emsp;Os recursos eram tão limitados que os conflitos internos e disputas por territórios se tornavam inevitáveis. As escaramuças pela água ou por pequenas áreas de sombra tornavam-se frequentes, levando a um ciclo interminável de animosidade e retaliação.<br/><br/>
            
            <strong>Linhagens das areias</strong><br/>
            &emsp;&emsp;A diversidade cultural das areias era um dos pilares que sustentava a vitalidade do reino, enriquecido por raças singulares dotadas de habilidades místicas extraordinárias. Essas raças, com suas contribuições únicas, eram responsáveis por transformar o deserto em uma terra de oportunidades. Com suas aptidões notáveis, desempenhavam papéis essenciais na sobrevivência e prosperidade do reino. Desde a habilidade de controlar os ventos que moldavam as dunas até a capacidade de encontrar água nas profundezas da aridez, essas raças magníficas garantiam a subsistência e o florescimento do reino. Cada uma delas, com suas características e talentos distintos, tecia uma tapeçaria de habilidades que era crucial para a harmonia e resiliência do lugar.<br/><br/>

            <strong>A Luta pela Dignidade</strong><br/>
            &emsp;&emsp;Para os habitantes da Terra das Areias, cada dia era uma batalha pela dignidade humana. A escassez de alimentos levava muitos a fazerem escolhas impensáveis. O canibalismo, embora um tabu extremo, tornava-se uma opção de último recurso quando a sobrevivência estava em jogo. Esse ato de desespero deixava marcas profundas na alma das pessoas, um lembrete sombrio do quão longe haviam caído.<br/>
            &emsp;&emsp;As crianças cresciam conhecendo apenas a luta e o sofrimento. Suas brincadeiras eram frequentemente interrompidas por gritos de alerta e pela urgência de se esconderem das ameaças noturnas. Seus sonhos eram povoados por monstros, e suas esperanças, moldadas por um futuro incerto.<br/><br/>
            
            <strong>Uma Terra de Contrastes</strong><br/>
            &emsp;&emsp;Apesar da dureza da vida, havia momentos de beleza efêmera. O nascer do sol pintava as dunas com cores vibrantes, e as noites estreladas ofereciam um vislumbre da vastidão do universo. Essas raras ocasiões de paz eram um bálsamo para as almas cansadas, uma pausa breve na constante luta pela sobrevivência.<br/>
            &emsp;&emsp;O deserto, com sua desolação e desafios, era um teste de resistência e vontade. As dificuldades que enfrentavam forçavam cada indivíduo a confrontar seus limites, e para aqueles que sonhavam com um futuro melhor, o deserto era tanto um obstáculo quanto uma oportunidade de passagem para o pós-morte.<br/><br/>

            <strong>A União das Tribos</strong><br/>
            &emsp;&emsp;Em uma noite gélida, uma tempestade de areia varreu o deserto com uma fúria indescritível. O vento, poderoso e implacável, levantava muros de areia que engoliam tendas e vilarejos inteiros, apagando em horas o que as tribos tinham levado anos para construir. Mas do caos e da destruição, surgiu uma oportunidade inesperada.<br/>
            &emsp;&emsp;Uma tempestade trouxe um terror tão grande que obrigou as tribos a se unirem em sua luta pela sobrevivência. Quando a areia finalmente se assentou, os líderes das tribos se encontraram, impulsionados pelo desespero e por uma compreensão compartilhada de que precisavam uns dos outros para enfrentar a ameaça das criaturas noturnas. O que começou como uma aliança de necessidade rapidamente se transformou em um compromisso de transformar seu destino.<br/>
            &emsp;&emsp;Naquela noite, as tribos descobriram não apenas a força, mas também a esperança. Juntas, começaram a desenvolver novas táticas de defesa e combate, combinando o conhecimento e as habilidades únicas de cada grupo. O que antes era uma luta solitária tornou-se um esforço compartilhado, e as criaturas, que antes pareciam invencíveis, começaram a recuar diante da resistência organizada das tribos.<br/>
            &emsp;&emsp;A vida naquele lugar começou a mudar. Embora a miséria extrema tivesse se transformado em pobreza, para aqueles que antes viviam em completo desespero, isso significava uma vitória significativa. A união permitiu que as tribos trocassem conhecimentos e aprimorassem suas técnicas de sobrevivência, compartilhando recursos e cuidando umas das outras. As fogueiras, que antes iluminavam rostos sombrios e cheios de medo, agora eram cercadas por conversas animadas sobre estratégias, histórias de coragem e esperanças de um futuro melhor.<br/>
            &emsp;&emsp;As crianças, que antes cresciam apenas conhecendo a luta e o sofrimento, começaram a ver novas possibilidades. Elas brincavam juntas, aprendendo umas com as outras, enquanto os anciãos compartilhavam sabedoria e histórias de tempos antigos que inspiravam todos a acreditar em dias mais brilhantes.<br/>
            &emsp;&emsp;Então a desolação do passado começou a dar lugar a uma nova era de cooperação e desenvolvimento. As tribos, antes presas em um ciclo de isolamento e sofrimento, encontraram força na união e resiliência na esperança. Al-Miraje, embora ainda enfrentasse muitos desafios, começou a vislumbrar um futuro onde a compaixão e a solidariedade pudessem finalmente florescer em meio às areias infinitas, transformando um deserto inóspito em um lar onde o espírito humano pudesse prosperar.<br/><br/>

            <strong>O Nascimento de Khalid</strong><br/>
            &emsp;&emsp;Sob um céu carregado de nuvens escuras, nasceu Khalid, um filho destinado a mudar o destino do Povo das Areias. Este conto se inicia a partir que uma mulher extraordinária chamada Laurel Solis se manifesta, cujo nome era tão resplandecente quanto sua presença.<br/>
            &emsp;&emsp;Laurel era uma mulher de beleza singular, marcada por cabelos crespos que dançavam ao vento como chamas douradas sob o sol do deserto. Sua pele, profundamente dourada pelo escaldante sol do deserto, irradiava um brilho cálido que refletia sua conexão com a terra que habitava. Essa conexão lhe conferia uma aura de força e resistência, características que ela trazia consigo em cada passo que dava.<br/>
            &emsp;&emsp;Em seus olhos, havia um desejo profundo, uma chama que ardia com intensidade e determinação. Esse desejo era tanto uma força impulsionadora quanto uma promessa, uma visão de um futuro melhor que ela estava determinada a realizar. Era um olhar que não apenas enxergava as dificuldades, mas também as possibilidades ocultas, os sonhos ainda por se concretizarem. Seu destino estava intrinsecamente ligado às cinco tribos nômades que habitavam as areias do deserto.<br/>
            &emsp;&emsp;Laurel era uma figura de beleza rara e inteligência perspicaz, uma mulher que desafiava as normas tradicionais de sua época. Desde jovem, ela viajava entre as tribos, aprendendo suas histórias e culturas, mesmo em meio à desgraça. Seu carisma e sabedoria eram tão notáveis que rapidamente conquistaram a admiração e o respeito de muitos líderes tribais.<br/>
            &emsp;&emsp;Outrora, uma figura feminina e majestosa, de cabelos dourados como o ouro e vestimentas tão obscuras quanto a noite que surgiu durante a noite naquele local pediu água para Laurel e a mesma a serviu. Após agradecer por saciar sua sede, a mulher entrou em um estado de transe e com um olhar penetrante, ela proclamou uma premonição em um tom uníssono: “Bendito seja a árvore que tens em ti, ela gerará o fruto dos frutos, a maçã dourada que trará prosperidade a esta terra de lamentos.”, e ao finalizar das palavras a mulher de cabelos dourados assim como uma nuvem se dissipou, sumindo diante os olhos da futura mamãe. Esse encontro místico acendeu em Laurel uma determinação inabalável de cumprir esse destino e o medo de como poderia ser feito.<br/>
            &emsp;&emsp;Impulsionada pela profecia, Laurel começou a despertar o interesse de cada líder tribal, usando sua inteligência e charme. Ela se deitou com eles separadamente, conhecendo seus corações e desejos. No entanto, essa aproximação causou uma tensão crescente entre os líderes, levando-os a uma briga interna pelo seu afeto.<br/>
            &emsp;&emsp;Para evitar um conflito devastador entre as tribos recém-unidas, Laurel revelou a verdade sobre a profecia e propôs uma solução sem precedentes: um relacionamento estratégico e poliamoroso com todos os cinco líderes. Sua visão era de união e força através do amor e respeito mútuo. Reconhecendo a sabedoria em suas palavras e a oportunidade de paz e prosperidade, cada líder aceitou essa aliança inovadora. Assim, Laurel tornou-se a esposa de todos os cinco, formando um laço que uniu as tribos para sempre.<br/>
            &emsp;&emsp;Dessa união única, nasceu Khalid. Ele foi criado sob a orientação e amor de seus pais, cada um representando uma parte da rica tapeçaria cultural implantada ali. A criança cresceu em um ambiente repleto de diversidade, aprendizado e amor, que moldou seu caráter e instigou nele um profundo desejo de unir seu povo e comandar a todos.<br/><br/>

            <strong>O Ascenso ao Poder</strong><br/>
            &emsp;&emsp;À medida que o pequeno rei crescia, ele herdou não apenas a sabedoria e o conhecimento de seus pais, mas também a responsabilidade de concretizar a visão de Laurel. Sua infância foi marcada pela pobreza, mas sua curiosidade insaciável e inteligência precoce destacaram-no desde cedo. Ele se dedicou ao estudo da alquimia e da magia, fascinado pela possibilidade de mudar o destino de seu povo.<br/>
            &emsp;&emsp;Khalid buscava incessantemente por respostas nos pergaminhos antigos e junto aos magos viajantes, determinado a descobrir o segredo da transmutação. Ele acreditava que, ao transformar areia em ouro, poderia erradicar a pobreza que ainda assolava Al-Miraje e unir seu povo em prosperidade.<br/>
            &emsp;&emsp;Após anos de intensos estudos e experimentos e até mesmo conhecer sábios viajantes, O promissor finalmente descobriu a fórmula que permitia transformar areia em ouro. Com esse conhecimento em suas mãos, o mesmo rapidamente usou a nova riqueza para realizar os sonhos de sua mãe e dos líderes tribais. Ele iniciou a construção de estradas pavimentadas, ergueu edifícios majestosos e estabeleceu sistemas de educação e saúde para todos, coroando o povo com uma era digna de paz e prosperidade.<br/><br/>

            <strong>O Legado das Areias</strong><br/>
            &emsp;&emsp;Sob a liderança do prometido, o reino floresceu como nunca antes. As tribos que uma vez viveram na miséria e no medo agora prosperavam em uma terra de oportunidades e paz. O coroado investiu na educação de seu povo, assegurando que cada indivíduo tivesse acesso ao conhecimento e às ferramentas necessárias para construir um futuro melhor.<br/>
            &emsp;&emsp;A transformação de uma terra desolada em um oásis de opulência foi testemunho do poder da união. Ele era um líder visionário, cuja habilidade de transformar areia em ouro simbolizava não apenas sua maestria nas artes mágicas, mas também sua determinação em criar um legado de paz e prosperidade.<br/>
            &emsp;&emsp;Khalid, o imperador alquimista, é lembrado como um messias, uma figura que trouxe esperança e mudança duradoura para aquele mundo de areia.
        </p>


        `
    },
    {
        img: "livro7.png",
        title: "Umbrovea",
        text: `
          
        <h1>REINOS</h1>
        <h2>UMBROVEA</h2>

        <p>
            &emsp;&emsp;<span class="first-letter">E</span>m tempos remotos, Umbrovea era conhecida como a Floresta Negra, uma terra sem lei e dominada pelos desejos insaciáveis da Primeira Rainha. A região era habitada por criaturas noturnas guiadas pelo instinto. Visitar esta terra à noite era impossível, pois criaturas selvagens, ferozes e abissais se erguiam do mais profundo buraco para consumir e se alimentar.<br/>
            &emsp;&emsp;Contudo, há mais de mil anos, um embate entre mãe e filha gerou um cataclisma mágico sem precedentes, dilacerando a fronteira entre os mundos material e espiritual, fundindo-os em um turbilhão caótico após o uso de forças primordiais. Num instante, toda vida foi erradicada, transmutada em algo novo, desafiando as próprias leis da existência e impregnando fauna e flora com uma essência estranha que era altamente convidativa para as criaturas das trevas, enfatizando a ascensão da nova rainha e erradicando a antecessora.<br/>
            &emsp;&emsp;A geografia de Umbrovea foi grotescamente alterada, distorcida e moldada por uma magia singular que pulsa simulando um coração maligno no centro da extinta Floresta Negra. Então, assim, os Soberanos foram denominados para servirem a coroa, agraciados cada um com uma Joia do Oculto para terem absoluto controle sobre suas regiões e até mesmo ostentam a marca da família real em sua testa. Árvores sussurram segredos obscuros, enquanto as sombras parecem ganhar vida própria, espreitando intrépidos que se aventuram em seus domínios interditos. Qualquer mortal que ouse penetrar nestes litorais sinistros experimentará sua vitalidade sendo sorvida lentamente, um sopro gélido insinuando-se nos ossos. Este dreno vital atrai espíritos insaciáveis e atormentados dos mortos, que deambulam incansáveis, seus lamentos ecoando pela escuridão.<br/>
            &emsp;&emsp;A prisionados entre os reinos dos vivos e dos mortos, esses espectros são impelidos por um desejo voraz de consumir a vitalidade dos incautos que adentram a terra agora amaldiçoada. Perecer na névoa negra é condenar-se a assombrar este lugar lúgubre por toda a eternidade, um destino mais tenebroso do que a própria morte. As almas dos caídos fundem-se à paisagem espectral, alimentando um ciclo incessante de desespero e aflição. E, para agravar a situação, o poder que agora impera parece crescer e fortalecer-se com o passar dos anos.<br/>
            &emsp;&emsp;À medida que sua influência se expande, os espectros mais poderosos conseguem estender seus domínios cada vez mais longe pelo mundo, propagando a escuridão e o teor assombroso que antes eram contidos nos confins da região. Este lugar, outrora um lugar selvagem, transformou-se num domínio onde a esperança foi eclipsada, substituída por um reino de eterno mistério sombrio. Contos sobre este reino são murmurados com temor, e os raros que retornam de suas fronteiras trazem consigo relatos de visões aterrorizantes e abominações inomináveis, reforçando a crença de que esta terra enfeitiçada é um ponto onde o mundo dos vivos se entrelaça de forma irremediável com o reino dos mortos.
        </p>

        <p>
            &emsp;&emsp;<span class="first-letter">H</span>oje, Umbrovea é o berço de seres das trevas, sendo composta por algumas regiões, cada uma com suas próprias características sombrias.<br/>
            &emsp;&emsp;Gran Goecian É uma terra onde os segredos do passado se entrelaçam com as promessas do futuro. Sob a vigilância constante dos Soberanos, esta região é um monumento à grandiosidade e à história do reino, um farol de poder que ilumina as sombras ao seu redor. A Torre Real se ergue como uma sentinela antiga, e as árvores rubras serpenteiam entre o edifício grandioso e imponente. Festas assombrosas, banquetes opulentos e torneios são realizados com frequência, reforçando Gran Goecian como o coração pulsante do Mundo das Sombras.  <br/>
            &emsp;&emsp;Volupinea é presidida pelo segundo Overlord e é um domínio onde deleites e excessos se entrelaçam em uma dança sedutora. A atmosfera de luxúria e decadência permeia a região, com uma torre irradiando volúpia, dançarinas hipnotizantes, um bar soturno e arenas de luta sangrentas. Cada esquina oferece tentação e perigo, e por trás da fachada de prazer, há uma escuridão espreitando, pronta para engolir os desavisados.  <br/>
            &emsp;&emsp;Sudratanea é uma terra envolta em fogo e mistério, governada pelo terceiro Overlord. Chamas eternas dançam em uma sinfonia de calor e destruição, alimentando forjas negras que consomem tudo em seu caminho. Os guerreiros de Sudratanea, conhecidos como os Incandescentes, são a personificação da fúria e da vontade de lutar. Eles são guardiões de Umbrovea, uma força inquebrantável que mantém as trevas seguras com o uso de seus sentimentos flamejantes.  <br/>
            &emsp;&emsp;Abissinea é um reduto de mistério e magia obscura, onde a escuridão é uma entidade viva e pulsante. Governada pelo terceiro Overlord, Abissinea abriga a Biblioteca Profana, guardada pelos Sussurrantes, seres etéreos. A floresta assombrada desta região abrigam criaturas das trevas que tecem suas tramas e devoram suas vítimas lentamente, até mesmo durante a noite se é capaz de ouvir gritos e gemidos vindos de lá. Este é o domínio repleto de paradoxos e enigmas, onde a verdade está sempre oculta nas sombras que a Guerra Antiga forjou.  <br/>
            &emsp;&emsp;Carnificidea é uma região pulsante e viva, completamente consumida por uma infecção constante conhecida como Noxrégia. Aqui, a própria terra parece respirar, vibrando com uma energia sombria e inquietante. O solo é coberto por uma vegetação mutante que se contorce, emitindo uma luz avermelhada que cria uma atmosfera de constante inquietação.  <br/>
            &emsp;&emsp;A paisagem é instável, com protuberâncias que se erguem e retraem como se fossem pulmões. A flora é composta por plantas mutantes, exalando um aroma adocicado e venenoso que intoxica os incautos. As árvores têm galhos retorcidos que parecem agarrar o céu, e algumas sussurram palavras de desespero aos passantes, como se contassem segredos de um pesadelo eterno.  <br/>
            &emsp;&emsp;Os seres que habitam Carnificidea são produtos do grandioso fungo, transformados em grotescas aberrações de seus antigos eus. Esses monstros que vagam pela região são ex-humanos ou animais fundidos com a infecção. Outros também são originários do líquido materno da criatura ancestral que deu origem ao Noxrégia. São imprevisíveis e hostis, sempre em busca de novas vítimas para alimentar o fungo que lentamente se alastra pela região, expandindo seu domínio, até mesmo se é capaz de dizer que este ser tem consciência própria.  <br/>
        </p>

        `
    },
    {
        img: "livro1.png",
        title: "Ydris",
        text: `
          
        <h1>REINOS</h1>
        <h2>YDRIS</h2>

        <p>
            &emsp;&emsp;<span class="first-letter">N</span>o início dos tempos, quando o mundo ainda estava sendo moldado pelas mãos dos deuses, o reino de Ydris emergiu como um farol de espiritualidade e devoção. Segundo o "Almanaque Divino", a terra de Ydris foi abençoada pelos deuses antigos, cujas manifestações divinas moldaram o destino dos habitantes e estabeleceram as bases para uma religião profundamente enraizada.<br/>
            &emsp;&emsp;O "Almanaque Divino" descrevia os deuses com precisão vibrante: Milodrye, a deusa do amor e dos prazeres; Uitar, o deus da luz e da beleza; e Khefos, o deus da abundância. Cada deus tinha seu papel sagrado na vida cotidiana dos Ydrianos, e suas histórias eram passadas de geração em geração, solidificando uma devoção fervorosa entre os habitantes. O culto a esses deuses era não apenas uma prática religiosa, mas uma parte intrínseca da identidade cultural e social de Ydris.<br/>
            &emsp;&emsp;Durante a Era da Iluminação, o sacerdote Lorkan trouxe uma transformação radical à religião de Ydris. Em uma experiência transcendental, Lorkan revelou que os deuses antigos eram aspectos de uma entidade universal única, manifestada em sete formas distintas. Ele fundou a Igreja dos Sete, cujos ensinamentos enfatizavam a unidade divina e a iluminação espiritual.<br/>
            &emsp;&emsp;A nova doutrina desafiou as tradições estabelecidas, promovendo a ideia de um Deus unificado em vez de múltiplos deuses separados. A Igreja dos Sete cresceu rapidamente, estabelecendo templos e centros de sabedoria por todo o reino. A mensagem de Lorkan ressoou profundamente entre os Ydrianos, que viam essa revelação como uma forma de alcançar uma compreensão mais profunda do divino.<br/>
            &emsp;&emsp;Ydris se estabeleceu como um reino devotado à sua religião, onde a prática espiritual e a adoração ocupavam um lugar central na vida cotidiana. A sociedade ydriana era marcada por uma devoção fervorosa e uma estrita adesão às tradições religiosas. Os templos dedicados aos Sete se erguiam majestosos em todas as cidades e vilarejos, e os sacerdotes da Igreja dos Sete eram figuras de grande respeito e influência.<br/>
            &emsp;&emsp;A religião moldava todos os aspectos da vida em Ydris. As festividades religiosas, os rituais diários e as celebrações em honra dos Sete eram eventos importantes que uniam a comunidade e reforçavam a coesão social. Cada aspecto da vida, desde a agricultura até a educação, era permeado pela crença na iluminação divina.<br/>
            &emsp;&emsp;Despite de ser um reino pacífico, Ydris era extremamente conservador devido à sua fervorosa devoção religiosa. As normas sociais e os costumes eram rígidos, refletindo uma profunda reverência pelas tradições estabelecidas. Mudanças na prática religiosa ou novos pensamentos eram frequentemente recebidos com resistência.<br/>
            &emsp;&emsp;O governo de Ydris estava intrinsecamente ligado à religião. Os líderes políticos eram muitas vezes também sacerdotes, e suas decisões eram guiadas pelos princípios dos Sete. As leis e políticas do reino eram moldadas para refletir os ensinamentos da Igreja, e a justiça era administrada de acordo com a moralidade religiosa.<br/>
            &emsp;&emsp;Apesar da harmonia interna e da paz relativa, o reino enfrentava desafios derivados de sua natureza conservadora. O isolamento cultural e a resistência à mudança podiam levar a tensões com reinos vizinhos que seguiam tradições diferentes ou que eram mais progressistas. A proteção das tradições e da ordem social muitas vezes exigia um equilíbrio delicado entre manter a coesão interna e interagir com o mundo exterior.<br/>
            &emsp;&emsp;O legado de Lorkan e a fundação da Igreja dos Sete permaneceram como pilares centrais da identidade de Ydris. A busca pela iluminação e pela verdade continuava a inspirar os habitantes, e a religião fornecia um sentido profundo de propósito e pertencimento. Embora o reino permanecesse conservador e profundamente enraizado em suas tradições, a essência da fé ydriana servia como uma fonte de força e estabilidade para a nação.<br/>
            &emsp;&emsp;À medida que o futuro se desenrolava, Ydris permanecia como um reino onde a fé e a tradição se entrelaçavam para formar uma sociedade única e coesa. A prática espiritual e a devoção contínua garantiam que o legado dos Sete e a busca pela iluminação continuassem a iluminar o caminho para as futuras gerações.
        </p>
        `
    },
    {
        img: "livro5.png",
        title: "A Queda de Al-Miraje",
        text: `
          
        <h1>AL-MIRAJE</h1>
        <h2>A queda de um império</h2>
        <br/>
        <p>
            &emsp;&emsp;<span class="first-letter">A</span> <strong>Ascensão da Loucura</strong><br/>
            &emsp;&emsp;Durante a era dourada de seu reinado, o soberano desfrutava de um poder que parecia ilimitado. No entanto, com a paz e a prosperidade surgiu uma inquietação crescente, plantada por um de seus sábios. A ideia de que sua grandeza poderia definhar conforme sua idade alimentou um desejo insaciável de domínio das forças místicas para reverter suas condições mortais. Com convicção de que só ele podia conduzir todos a um futuro próspero, como já havia feito uma vez, o mesmo estava decidido a dominar e, pela força, apropriar-se dos conhecimentos dos reinos vizinhos para seu próprio benefício, até mesmo enxergava-se como benevolente pois todos agora viveriam agraciados pela sua visão de mundo e comando. Esta crença enfatizada por um sussurro malicioso, tomou força por uma infância marcada pela adulação, então transformou-o em um líder obcecado pela expansão.<br/>
            &emsp;&emsp;As ideias distorcidas e o desejo de imortalidade passaram a consumir sua mente. Agora atormentado por desejos imorais, vislumbrava não apenas a perpetuidade de seu domínio, mas o controle sobre todos os reinos conhecidos. O território das areias, um dia um farol de beleza e justiça, começou a ser moldado pela visão distorcida de seu governante.<br/><br/>
            &emsp;&emsp;<span class="first-letter">O</span> <strong>Império em Ruínas</strong><br/>
            &emsp;&emsp;À medida que sua paranoia e ambição cresceram, o monarca lançou uma série de campanhas expansionistas destinadas a dominar os reinos vizinhos. Seu desejo de conquista levou-o a invadir Aetherya, Umbrovea e Ydris, acreditando que sua missão era unir todos sob seu domínio absoluto.<br/>
            A primeira incursão foi em Aetherya, um reino conhecido por suas paisagens exuberantes e cultura vibrante. Com suas tropas implacáveis, o conquistador devastou as terras férteis, destruindo campos e tentou forçar os habitantes a se submeterem ao seu regime. A resistência local, entretanto, foi mais feroz do que ele esperava. Usando o conhecimento íntimo de suas florestas, os aetheryanos realizaram emboscadas e ataques surpresa, desgastando as forças do invasor. Os líderes locais, mestres em estratégias de guerrilha, uniram tribos e comunidades em uma frente unificada, utilizando a topografia variada da região para emboscar e desmoralizar as tropas inimigas. Após meses de batalha, os exércitos do conquistador foram forçados a recuar, deixando para trás um rastro de destruição, mas também uma lição amarga sobre a resiliência e determinação do povo élfico.<br/>
            Em Umbrovea, o exército do imperador enfrentou uma resistência implacável. A terra assombrada não se deixou subjugar facilmente. Em sua busca desesperada por poder, o governante ordenou a erradicação da escuridão da região, acreditando que ao submeter os espíritos defensores, poderia dominar o reino. Suas ordens desencadearam uma guerra brutal, atraindo a fúria dos Lordes de Umbrovea. Esses seres, conhecidos por sua ferocidade, reagiram com violência implacável, derrotando suas tropas e enviando cabeças decapitadas como um aviso severo. A derrota humilhante frustrou suas ambições expansionistas e desfez suas esperanças de subjugar as sombras do Reino das Sombras.<br/>
            A invasão de Ydris foi a mais desafiadora das campanhas. Obcecado por poder absoluto, o soberano atacou com brutalidade, mirando nas bibliotecas e templos que representavam a sabedoria e honra daquela região. Apesar da destruição, os habitantes, liderados por defensores imponentes, resistiram com bravura. O ataque resultou apenas em danos parciais às instituições de fé, sem que o reino fosse conquistado. A derrota em Ydris marcou o fim de suas ambições expansionistas, deixando contos sobre a frustração em meio às areias.<br/><br/>
            &emsp;&emsp;<span class="first-letter">Os</span> <strong>Conselhos de um Sábio</strong><br/>
            &emsp;&emsp;A busca insaciável por poder do rei levou-o a explorar conhecimentos proibidos oferecidos de bom grado pela Irmandade de Sábios que ali habitavam, sendo estas escrituras totalmente instáveis. Atraído pelas promessas de imortalidade e domínio absoluto, ele começou a estudar em papiros repletos de poeira e areia, até mesmo se envolver em rituais sombrios, acreditando que esses conhecimentos lhe concederiam a força necessária para submeter os reinos vizinhos com total êxito. No entanto, ao mergulhar mais fundo naquele abismo abstrato, o rei desencadeou inadvertidamente forças que seus olhos não podiam compreender e com isso trouxeram infortúnios terríveis para suas terras. Os rituais que deveriam fortalecê-lo abriram portas para entidades destrutivas, e uma maldição começou a se espalhar pelo reino. Onde antes havia prosperidade, agora reinava a desolação. O solo fértil secou, as colheitas apodreceram, e um medo crescente tomou conta do povo. O governante, cegado pela obsessão, não percebeu que, ao buscar controlar as forças do caos, ele havia selado o destino de seu império, mergulhando-o em um ciclo de decadência e desespero.<br/><br/>
            &emsp;&emsp;<span class="first-letter">O</span> <strong>Declínio do Império</strong><br/>
            &emsp;&emsp;No tempo em que o governante expandia seu domínio, sua própria terra começou a sofrer as consequências de sua tirania e dos atos macabros. O reino das areias, outrora próspero, mergulhou em um estado de declínio. A escassez de recursos e a fome espalharam-se como uma praga, enquanto o povo sofria sob a opressão do imperador.<br/>
            A corrupção moral e a busca insaciável por poder desestabilizaram o próprio império. A desolação e o terror tornaram-se parte do cotidiano, e a antiga grandiosidade do reino foi substituída por um território em ruínas.<br/><br/>
            &emsp;&emsp;<span class="first-letter">O</span> <strong>Confronto</strong><br/>
            &emsp;&emsp;À medida que a cidade se afundava na devastação, o imperador mergulhava em uma loucura cada vez mais extrema. O rei passou a absorver toda a culpa e o ódio gerados por seus atos ao ver o estado que as coisas estavam. Sua mente, corroída pelo desespero e pela influência sombria do Sábio, deu lugar a uma transformação horrenda.<br/>
            O governante, antes um homem de grande estatura e dignidade, transformou-se em uma monstruosidade grotesca. Seu corpo majestoso tornou-se uma massa deformada de carne e sombra, coberta por uma pele escura e viscosa. Seus olhos, antes cheios de ambição e sabedoria, transformaram-se em poços de fúria insana e crueldade. Com cada monumento e palácio que devorava, a figura monstruosa tornava-se ainda mais grotesca e ameaçadora, engolindo a cidade que um dia governará com orgulho.<br/>
            Os edifícios esplendorosos, agora sob o ataque implacável do imperador monstruoso, desmoronavam em uma cascata de destroços e ruínas. A cidade, que antes brilhava com a luz da civilização e da cultura, estava agora envolta em um manto de destruição e desespero. O governante, em sua nova forma, se movia como um titã enfurecido, destruindo tudo o que encontrava, cada pedaço da cidade sendo consumido por sua voracidade insaciável.<br/>
            Foi nesse momento de confusão absoluta que uma silhueta feminina surgiu das sombras. Vestida com um manto escuro, seus cabelos dourados brilhavam como um farol de esperança em meio à podridão que tomava conta do lugar. Essa figura se tornava a última linha de defesa contra a terrível transformação do soberano. Sua presença era um vislumbre de luz em um mundo mergulhado no medo mais profundo. Pouco depois, outras duas mulheres surgiram para apoiá-la, permitindo que alguns habitantes fugissem daquele horror.<br/>
            As três mulheres uniram forças e começaram a proferir palavras de poder, criando correntes elementais provenientes da terra que subjugaram a criatura ao chão. Juntas, iniciaram uma melodia uníssona, uma magia poderosa e proibida que selaria o império para sempre. Durante a batalha desesperada, as três lançaram feixes multicoloridos, capazes de queimar a carne mais densa. Cada feitiço que tentava conter a fúria monstruosa parecia apenas alimentá-la, enquanto o governante se enfurecia ainda mais, sua forma grotesca devorando os vestígios do antigo reino.<br/>
            À medida que as mulheres lutavam com bravura, os espíritos das pessoas sacrificadas começaram a se manifestar ao seu redor. Suas almas, unidas em uma sinfonia macabra e etérea, enchiam o ar com um lamento de dor e tristeza. A magia da cristalização foi concluída como um grito de guerra, uma explosão de luz que envolveu todo o território.<br/>
            O grandioso rei foi cristalizado vivo no lugar, sua forma deformada transformada em uma estátua, preservada como uma cápsula do tempo. Cada ruína de palácio e torre, um dia símbolo da grandeza, agora eram monumentos à queda do reino que com aquele peso absurdo afundou em meio às areias.<br/>
            E assim território submerso nas profundezas do deserto tornou-se uma lenda. A cidade e seu governante caído serviram como um aviso sombrio para aqueles que buscavam poder absoluto através de forças desconhecidas. As mulheres que surgiram como graças trouxeram um silêncio eternamente duradouro, mas também um legado de advertência sobre os limites que não devem ser ultrapassados pelos mortais. Então, a história do reino e de seu imperador monstruoso perdura como um eco das sombras e das glórias que uma vez foram, na vastidão do deserto esquecida.
        </p>

        `
    },
    {
        img: "livro8.png",
        title: "A manifestação da Fé",
        text: `
          
        <h1>RELIGIÃO</h1>
        <h2>A FÉ DOS SETE</h2>

        <p style="margin: 0; padding: 0;">
            <strong>Capítulo 01:</strong> O Almanaque Divino – A Origem dos Deuses<br/><br/>
            Em tempos antigos, antes que as sombras se tornassem luz e a luz, sombra, a crença na religião de Ydris era descrita em um texto sagrado conhecido como o "Almanaque Divino". Este relato ancestral delineava um mundo onde deuses antigos, cada um com um nome, rosto e propósito distintos, governavam e moldavam o destino dos mortais.<br/>
            O Almanaque Divino começava com a descrição dos deuses em sua forma mais pura e personificada. Cada divindade era apresentada com uma riqueza de detalhes que visavam tornar o incompreensível mais tangível para os sentidos humanos limitados. Havia, entre eles, a majestosa Milodrye, deusa do amor e dos prazeres carnais, cujo rosto era adornado com rosas e cujo toque prometia despertar desejos profundos. Em contraste, Uitar, o deus da luz e da beleza, era retratado com uma aura resplandecente, um reflexo perfeito do Sol que iluminava a escuridão com clareza imaculada. Khefos, o deus da abundância, era representado com um semblante jovial, rodeado de banquetes e festividades que simbolizavam sua influência sobre a culinária e a riqueza.<br/>
            Cada deus possuía um propósito distinto e uma esfera de influência própria. As narrativas do Almanaque Divino detalhavam como esses deuses interagiam com o mundo e com os mortais, oferecendo-lhes orientação, proteção ou desafios, conforme seu domínio e vontade.<br/>
            Contudo, mesmo enquanto as crenças eram estabelecidas e os cultos aos deuses antigos ganhavam força, surgiam questionamentos profundos sobre a natureza da divindade. A figura do autor do "O Legado dos Deuses Ancestrais", um escritor venerado por sua sabedoria e reflexão, introduziu um ponto de vista que começou a permear a narrativa do Almanaque Divino.<br/>
            Este autor questionava a própria necessidade de atribuir aos deuses nomes e formas distintas. "Será que estamos apenas atribuindo aos deuses nomes e formas para tornar o incompreensível mais tangível aos nossos sentidos limitados?" – perguntava ele. Essa dúvida fazia parte de uma visão mais ampla sobre a natureza da divindade e a nossa capacidade de entendê-la.<br/>
            As palavras do autor sugeriam que os deuses poderiam ser algo além das formas e figuras que criamos para compreendê-los. Talvez, argumentava ele, a verdadeira essência do divino fosse algo que transcende as características que lhes atribuímos, algo que não poderia ser totalmente captado pelos nossos sentidos ou descrito em palavras. A visão questionadora refletia a ideia de que os deuses, em sua totalidade, poderiam ser uma força universal, incompreensível em sua plenitude, e que nossas representações eram meros reflexos ou representações limitadas da realidade maior.<br/>
            Apesar dessas dúvidas e questionamentos, a adoração aos deuses antigos continuava a prosperar. A necessidade humana de compreender o divino e encontrar sentido nas forças que moldavam o mundo era forte. Os cultos e rituais se mantinham, sustentados pela tradição e pela crença de que, mesmo que as representações divinas fossem imperfeitas, elas ofereciam uma conexão vital com o sagrado.<br/>
            Os templos ainda se erguiam em homenagem aos deuses individuais, e os sacerdotes continuavam a realizar rituais que buscavam invocar suas presenças e receber suas bênçãos. A tradição, muitas vezes, servia como um meio de manter a ordem e proporcionar um sentido de propósito e pertencimento aos fiéis, mesmo enquanto as dúvidas sobre a natureza verdadeira dos deuses persistiam.<br/>
            O Almanaque Divino, portanto, não era apenas um relato dos deuses e suas características, mas também um reflexo das complexas questões filosóficas e espirituais enfrentadas pelos adoradores. A visão questionadora do autor de "O Legado dos Deuses Ancestrais" introduziu uma camada de introspecção na religião de Ydris, incentivando os fiéis a refletirem sobre a profundidade da divindade e sobre a própria natureza da fé.<br/>
            Enquanto os cultos e tradições continuavam, o Velho Testamento permanecia como um testemunho das origens da religião de Ydris, uma lembrança de que a busca por entender o divino era uma jornada repleta de mistério e complexidade. As dúvidas e reflexões, longe de enfraquecer a fé, enriqueciam o tecido espiritual da religião, mostrando que o desejo de compreender o incompreensível é, em si, uma parte vital da experiência humana com o divino.<br/><br/>
            <strong>Capítulo 02:</strong> A Ascensão de Lorkan – O Mensageiro dos Sete<br/><br/>
            Em um tempo marcado pela busca incessante de compreensão espiritual e pela prática dos cultos aos deuses antigos, um evento transcendente irrompeu como um raio de luz em meio à penumbra das dúvidas. Este fenômeno não foi apenas um sinal de mudança, mas a manifestação de um novo caminho para a fé dos habitantes da Terra de Ydris. Era a ascensão de Lorkan, um sacerdote cuja profunda comunhão com os deuses lhe conferiu um status quase divino.<br/>
            Lorkan era um homem de extraordinária devoção e percepção espiritual. Desde jovem, ele demonstrou uma capacidade incomum de se conectar com o divino, realizando feitos que desafiavam a compreensão mortal. Seus seguidores contavam histórias de milagres e revelações que ele havia proporcionado, muitas vezes comparando-o a figuras sagradas das tradições passadas, como os profetas ou até mesmo a encarnação do sagrado.<br/>
            Um evento particularmente notável ocorreu durante uma noite de meditação profunda. Em um momento de intensa concentração e oração, Lorkan foi envolto por uma aura luminosa, e os céus abriram-se em um espetáculo de luz e cor que deslumbrava os presentes. Aqueles que testemunharam o fenômeno disseram que Lorkan parecia transcender seu corpo físico, seu espírito se fundindo com uma presença divina que emanava uma sensação de paz e poder incomensuráveis.<br/>
            Com sua ascensão, Lorkan trouxe uma nova revelação que transformaria a estrutura da fé em Ydris. Em sua visão sagrada, ele percebeu uma verdade profunda que transcendia as representações físicas e nominais dos deuses. Lorkan proclamou que a adoração antiga, com suas formas e figuras distintas, era uma expressão imperfeita da verdadeira natureza do divino. Em vez de deuses antigos com nomes e faces, ele ensinou que os deuses eram aspectos de uma única entidade universal, um corpo divino com sete braços, cada um representando uma força ou qualidade essencial que orientava os mortais.<br/>
            Essa visão revolucionária desafiava as tradições estabelecidas. Lorkan revelou que a verdadeira divindade não estava em formas e nomes específicos, mas na essência unificada que se manifestava através de cada aspecto do divino. Ele comparou isso à maneira como os sentimentos humanos, como o amor e a compaixão, não podiam ser totalmente personificados, mas eram experiências universais que conectavam todos os seres.<br/>
            Como um líder visionário, Lorkan fundou a primeira Igreja dos Sete, estabelecendo uma nova doutrina que refletia sua revelação divina. A Igreja dos Sete não se baseava na adoração de deuses individuais, mas na compreensão de uma força divina única que se manifestava em sete aspectos diferentes. Seus ensinamentos enfatizavam a unidade e a transcendência do divino, promovendo uma adoração que reconhecia a interconexão e a interdependência de todos os aspectos da divindade.<br/>
            Lorkan também escreveu as Leis dos Sete, um conjunto de preceitos que orientavam os seguidores a viver de acordo com os princípios da verdade, da clareza e da harmonia divina. Essas leis não apenas redefiniam a prática religiosa, mas também promoviam um novo entendimento sobre a relação entre o divino e o humano.<br/>
            Assim como os grandes profetas das tradições passadas, Lorkan continuou a realizar milagres que atestavam a veracidade de sua mensagem. Ele curava os enfermos, acalmava tempestades e oferecia sabedoria divina aos que buscavam orientação. Seus ensinamentos atraíam seguidores de todas as partes, e a Igreja dos Sete crescia rapidamente, espalhando a nova visão sobre o divino.<br/>
            Cada milagre e ensinamento de Lorkan servia para ilustrar a essência da nova doutrina – a ideia de que o divino é uma força unificada e transcendental que opera através dos sete aspectos, e que cada ser humano pode encontrar conexão e iluminação ao reconhecer e viver essa verdade.<br/>
            A ascensão de Lorkan e a fundação da Igreja dos Sete marcaram um ponto de virada na história da religião de Ydris. Apesar das mudanças significativas e das novas visões introduzidas, os cultos antigos não foram completamente abandonados, mas passaram a coexistir com a nova doutrina. A reverência pelos deuses antigos continuou a existir, mas agora era integrada a uma compreensão mais ampla da divindade como uma força universal e unificada.<br/>
            O impacto de Lorkan e de sua mensagem transformou o cenário religioso de Ydris e deixou um legado que continuaria a influenciar a espiritualidade e a prática religiosa por gerações futuras.<br/><br/>
            <strong>Capítulo 03:</strong> A Consolidação da Fé – A Era da Iluminação Universal<br/><br/>
            Com o tempo, a visão de Lorkan sobre a divindade, revelada através de sua ascensão e dos ensinamentos da Igreja dos Sete, transformou-se em um fundamento sólido da religião de Ydris. A nova doutrina, que estabeleceu a crença em um Deus único manifestado em sete aspectos, cresceu e se consolidou ao longo dos séculos, moldando a forma como os fiéis percebiam e interagiam com o divino.<br/>
            A Igreja dos Sete, inicialmente vista como uma inovação radical, tornou-se o núcleo espiritual da sociedade. Suas doutrinas e práticas ganharam aceitação e respeito, e sua influência se espalhou por regiões e culturas distantes. A mensagem de unidade e transcendência oferecida pelos Sete tocou profundamente os corações dos Ydrianos, proporcionando um sentido renovado de propósito e conexão.<br/>
            O princípio central da Igreja dos Sete é a iluminação. Esta crença sustenta que, embora as sombras sejam inevitáveis e necessárias para a existência da luz, é na luz que devemos buscar permanecer. A luz representa a verdade, a clareza e a harmonia que emanam da compreensão do divino como um todo unificado. A sombra, por outro lado, simboliza as dificuldades, as dúvidas e os desafios que fazem parte da experiência humana.<br/>
            Os ensinamentos da Igreja afirmam que, para afastar o caos e as trevas, os fiéis devem concentrar-se na luz e buscar a iluminação em todas as facetas de suas vidas. Isso implica uma busca contínua pela verdade, pela compreensão e pela prática de virtudes que refletem a essência dos Sete. A luz não é apenas uma metáfora para a divindade, mas também um guia prático para a conduta moral e espiritual dos indivíduos.<br/>
            A missão da Igreja dos Sete é clara e abrangente. Ela visa expandir a compreensão da iluminação universal e compartilhar seu conhecimento com todos os vilarejos de Ydris. Os líderes e sacerdotes da Igreja viajam incansavelmente pelas terras de Ydris, levando com eles a mensagem dos Sete e buscando construir pontes de entendimento e cooperação entre diferentes culturas e tradições.<br/>
            A Igreja promove uma abordagem inclusiva e diplomática, reconhecendo a diversidade das crenças e práticas ao mesmo tempo em que enfatiza os princípios universais que unem todas as formas de adoração. Através de diálogos inter-religiosos, intercâmbios culturais e esforços de ajuda humanitária, a Igreja busca criar um mundo mais harmonioso e pacífico, fundamentado na visão unificada dos Sete.<br/>
            Apesar de sua missão nobre, a Igreja dos Sete enfrentou desafios ao longo de sua história. A resistência de tradições antigas e a diversidade de crenças religiosas apresentaram obstáculos significativos. No entanto, a determinação e a sabedoria dos líderes da Igreja permitiram-lhes superar esses desafios, promovendo um entendimento mais profundo e uma aceitação gradual da nova visão.<br/>
            Uma das conquistas mais notáveis foi a construção de centros de sabedoria e iluminação, conhecidos como Templos da Luz. Esses centros servem como locais de aprendizado, meditação e práticas espirituais, oferecendo aos fiéis um espaço para explorar e aprofundar sua compreensão dos Sete. Eles também atuam como centros comunitários, promovendo a coesão social e o bem-estar entre as pessoas.<br/>
            A Igreja dos Sete continua a evoluir, com a esperança de que seu trabalho contribuirá para um mundo de paz e harmonia. O legado de Lorkan, que estabeleceu o caminho para a iluminação universal, vive através das ações e do compromisso contínuo dos fiéis. A visão de um mundo guiado pela luz e pela verdade permanece como um farol de esperança para as futuras gerações.<br/>
            Os seguidores dos Sete permanecem dedicados à missão de expandir o entendimento e promover a harmonia, acreditando que, apesar das sombras inevitáveis, a luz divina prevalecerá. Através de seus esforços incansáveis, a Igreja dos Sete busca iluminar os corações e as mentes dos mortais, promovendo uma era de paz e compreensão sob a visão unificada dos Sete.<br/>
        </p>

        `
    },
   
]