// eslint-disable-next-line import/no-anonymous-default-export
export default [
    {
        img: "background_preludio.jpg",
        title: "Prelúdio",
        text: `
          
        <h1>CAPÍTULO 01</h1>
        <h2>SERÁ O INÍCIO DO FIM?</h2>

        <p>
        &emsp;&emsp;<span class="first-letter">N</span>o vasto cenário de Yiridessa, somos transportados para um mundo pós-apocalíptico, onde as cicatrizes da guerra pelo poder se tornaram profundas fissuras nas relações entre as raças. Uma disputa feroz pelos territórios transformou cada centímetro do mapa em um campo de batalha, onde o controle significava a formação de exércitos imponentes que almejavam dominar o que agora chamamos de mundo. O anseio insaciável pelo poder, que permeava cada recanto, transcendia até mesmo os limites celestiais, ecoando entre os deuses ancestrais, que assistiam impotentes ao lento declínio do planeta Terra. À medida que os dias avançavam, a situação deteriorava-se, mergulhando a vida em um abismo. Pais, em um ato desesperado, sacrificavam seus próprios filhos por um mero pedaço de carne, enquanto maridos, cegados por promessas vazias de poder, entregavam suas esposas ao caos.<br/>
        &emsp;&emsp;<span class="first-letter">F</span>oi nesse contexto caótico que até mesmo os demônios mais perversos conhecidos por suas práticas canibais e apetites vorazes por outros demônios, insensíveis e sem preocupações, encontravam-se desesperados, ávidos por um aumento de poder que pudesse alterar o curso dos acontecimentos a seu favor.<br/>
        &emsp;&emsp;<span class="first-letter">E</span>xiste uma escassez significativa de informações sobre os deuses ancestrais - e quando menciono escassez, refiro-me a uma fração tão ínfima que até mesmo os mais antigos dentre nós são incapazes de mensurar a extensão de sua existência, suas origens ou o propósito subjacente à criação do universo. É verdadeiramente notável como algo de tamanha magnitude pode permanecer tão envolto em mistério. Os deuses ancestrais são entidades divinas e celestiais, cujo significado exato permanece elusivo; alguns os concebem como a própria essência da vida, enquanto outros os enxergam como a personificação do vazio primordial. A única certeza que temos é a existência de quatro dessas criaturas, embora jamais tenham sido avistadas por olhos mortais. Acredita-se que essas entidades divinas perambulem pelo infinito, dando origem a mundos em um ciclo interminável, onde a criação é seguida pela devastação causada pelos próprios habitantes do mundo.<br/>
        &emsp;&emsp;<span class="first-letter">V</span>estígios dispersos de informações sobre essas criaturas celestiais existem, porém, distinguir a verdade da ficção é uma empreitada verdadeiramente hercúlea, especialmente em um universo tão vasto quanto Yiridessa, onde charlatães proliferam. Os deuses ancestrais são dotados de onisciência, onipotência e onipresença, mas o que desejam que todos reconheçam é seu propósito primordial: a criação de mundos ao longo do infinito, durante sua jornada. Essa jornada segue um ciclo familiar: inicia-se com a criação do mundo, enquanto os ancestrais deixam sua marca na coordenada inicial, seguida pelo desenvolvimento do mundo enquanto transitam para o próximo ponto de criação, até culminar no fim do mundo, indicado pelos vestígios deixados para trás pelos ancestrais, que facilitarão o término daquela existência.<br/>
        &emsp;&emsp;<span class="first-letter">O</span>s deuses menores são estritamente proibidos de mencionar os ancestrais, sob pena de perderem suas vidas. Tal proibição sugere que os deuses ancestrais possuem uma magnitude de poder muito além do que se imagina superficialmente.<br/><br/>
        </p>
        <p>
         "Na profecia, o começo se revela através de flores impregnadas pelo doce aroma de canela,
        O riso de uma criança ressoa, ecoando nos recônditos de cada coração;
        Pétalas rosa dos girassóis pintam o prelúdio de uma vida por nascer.
        O princípio se entrelaça à compaixão entre pares,
        Empatia envolve cada ser no continente, despertando sensibilidade;
        O sabor adocicado de frutas sazonais e o desejo de compartilhá-las florescem.
        O início se concretiza no primeiro sorriso do inverno, tingido com lágrimas."
        </p>
        <br/><br/><br/>
        
        <h1>CAPÍTULO 02</h1>
        <h2>NÃO. NÃO EXISTIRÁ O FIM</h2>

        <p>
        &emsp;&emsp;<span class="first-letter">V</span>ocê já se deparou com relatos apocalípticos, histórias que proclamam o fim do mundo? Muitos as consideram falsas, meras fábulas destinadas a instilar o medo nos mais jovens. Se você optar por não acreditar, compreendo; não estou aqui para persuadi-lo. Tudo o que fizemos, cada ação que empreendemos, teve um único propósito: preservar a sua espécie de alguma maneira. É crucial compreender que tudo, absolutamente tudo, segue um ciclo. Os deuses, esses seres divinos que moldam nosso destino, fazem questão de nos recordar desse ciclo sempre que anseiam por nossa morte. Não são benevolentes; são egoístas, ávidos por clamor e adoração, pois é dessa reverência que extraem sua vitalidade. O mundo jamais findará, pois eles jamais permitirão que a fonte de sua energia se esgote. Contudo, atente-se ao ditado "Deus castiga", o mais verdadeiro dos aforismos. No instante em que sua devoção não for mais suficiente ou quando sua alma estiver comprometida, nada, absolutamente nada, o protegerá da ira divina. Seja prudente e siga a dança sugerida pelos deuses, ou arrisque perder algo vital, algo que jamais poderá ser recuperado. Talvez você nunca tenha refletido profundamente sobre isso; afinal, não é uma contemplação para qualquer mente.<br/>
        &emsp;&emsp;<span class="first-letter">A</span> narrativa do ciclo que conhecemos melhor, o da vida, permeia nossa existência, não é verdade? Nascemos, crescemos, desenvolvemos nossas jornadas, envelhecemos – seja com glória ou não – e, por fim, partimos. Este é um Ciclo. Todas as vicissitudes que ocorrem nesse intervalo não interrompem o ciclo; elas simplesmente são partes intrínsecas dele.<br/>
        &emsp;&emsp;<span class="first-letter">A</span>lguns se entregam a teorias e depositam fé no destino, acreditando que cada passo já está predestinado desde o nascimento. O que esquecem de compartilhar é que somos meras gotas em um vasto oceano chamado destino. O que acontece conosco, com nossos vizinhos ou com nossos interesses românticos não influencia algo ainda maior que se desdobrará para todos nós. Compreender que nossas vidas são um ciclo é vital, mas é imperativo expandir ainda mais nossa mente.<br/>
        &emsp;&emsp;<span class="first-letter">T</span>udo que conhecemos segue um ciclo. Acordar de manhã cedo, se alimentar, trabalhar e, então, retornar ao lar é um ciclo, seja uma rotina ou não. Separar-se de um parceiro romântico e iniciar um novo interesse é um ciclo, seja uma rotina ou não. O ciclo começa, se desenvolve, termina e, em sua maioria, recomeça. Ele NUNCA é interrompido, independentemente do que ocorre no percurso. A morte também se insere nesse ciclo; ela pode ser um recomeço, algo que talvez você ainda não tenha compreendido.<br/>
        &emsp;&emsp;<span class="first-letter">V</span>ocê percebe o que está acontecendo? Está confuso e precisa compreender as coisas abruptamente, e talvez tudo que estou compartilhando pareça fazer menos sentido do que esperava (ISSO É UM CICLO). Você talvez pense que estou louco, que estou delirando ou, no mínimo, tentando vender uma possível salvação para você neste mundo (ISSO FAZ PARTE DO CICLO, MESMO QUE PARA MIM SEJA UMA ROTINA). Nasce e morre, mas já percebeu que isso NÃO altera em nada o ciclo do universo em que vivemos? Nunca havia percebido, não é? Quanta arrogância. Exatamente, somos pequenos demais para compreender tudo isso.<br/><br/>
        </p>
        <p>
        “Na profecia, o término se revela com o desmatamento das florestas impregnadas pelo cheiro de enxofre;
        Os lamentos torturantes ecoam, provocados por presas e garras afiadas;
        Cada criatura derrama sangue sem um propósito claro, extinguindo suas vidas.
        O fim se insinua na falta de propósito em continuar a lutar por aqueles que ainda subsistem;
        Na apatia para auxiliar o próximo com gestos simples e descomplicados;
        Nos corações amargos daqueles que esqueceram como amar seus semelhantes - e até mesmo outros;
        O término se manifesta no sofrimento e na ausência de vitalidade. Necessitamos iniciar o ciclo novamente.”
        </p>
        <p>
        &emsp;&emsp;<span class="first-letter">E</span>stou aqui para partilhar contigo alguns conceitos. Agora que tens a essência do ciclo em mente, podemos ir além dessa "loucura" que compartilho. Antes de revelar o restante, é crucial compreendermos o que representam as trevas. Talvez já tenhas lido antigas narrativas em papiros sobre criaturas sanguessugas, seres caóticos corrompidos pelas litanias de suas raças, ou criaturas pouco pensantes ávidas apenas por se alimentar. Contudo, devo confessar um segredo: NADA disso realmente caracteriza as trevas. É verdade que não são criaturas benevolentes, amigáveis, que gostaríamos de ter em nosso convívio, mas a verdadeira ameaça que enfrentamos ultrapassa essas imagens. As trevas almejam muito mais do que simples atos caóticos. Elas não se importam nem consigo mesmas. Pode estar a questionar-se sobre o que exatamente desejam. Recordas-te de eu mencionar que nenhum ciclo pode ser interrompido? Pois bem, é isso que as trevas procuram: impedir que o fim encontre um novo começo, interromper o ciclo em sua jornada. Talvez agora me vejas como contraditório. "Disseste que nenhum ciclo pode ser interrompido...", e é exatamente isso. Nenhum ciclo pode ser interrompido, e estou aqui há muito tempo assegurando que assim seja. Sozinhas, as trevas não têm o poder de interromper o ciclo, mas as lendas da criadora maior indicam uma única alma que pode. A cada ciclo de nossa espécie, o sopro da vida nasce em uma pequena criatura capaz de destruir isso, mas as lendas não mencionam seu aparecimento.<br/>
        &emsp;&emsp;<span class="first-letter">A</span>s narrativas em papiros dos mais antigos descreviam os recomeços, embora fossem confusas e difíceis de acreditar. A esperança, contudo, persistia. As almas desapareciam com o primeiro sopro, mas os espólios permaneciam. Após milênios, o continente estava repovoado. Você percebe o ciclo recomeçando? O tempo passou, e os desafios retornaram. A harmonia entre criaturas era frágil, a amizade nem sempre prevalecia. No entanto, nada disso alterava nosso ciclo. O destino do universo estava novamente ameaçado pelas trevas, que corrompiam o solo de Yiridessa. As criaturas das trevas tomaram o controle, e eu, esgotado, tentei recomeçar, mas minha força se dissipou, e como poeira ao vento, deixei o continente contra minha vontade. Eu me perguntava por onde estavam os celestiais, por que construíam e não se preocupavam com a destruição? Os deuses menores, por que não estavam presentes em ajudar?<br/>
        &emsp;&emsp;<span class="first-letter">E</span>ra uma necessidade, uma tentativa de proteger esta dimensão da extinção iminente. Apesar de meu poder, as trevas persistiam em destruir os ciclos. Minha falha no último recomeço pareceu ser algo fora do ciclo. Os conselheiros, agora com um propósito restaurado, mantinham o rumo. O destino não era uma fantasia; ele existia. Se você está lendo isso, deve estar se perguntando como protegeremos os ciclos sem os Ancestrais. Minha alma ainda vaga pelo continente, parte essencial do ciclo, do recomeço. O mundo que conhecemos mudará sem essa renovação, mas vocês, sem interrupções, podem alterar o ciclo. Vocês precisam me encontrar antes que eu renasça para um novo ciclo. Se o recomeço falhar, eu não estarei aqui para contar essa história novamente, e ninguém estará vivo para ouvi-la. Depois dos acontecidos de Aetherya, ninguém ouviu mais falar sobre os guerreiros de jade, a escola de magia ou as bruxas, caso não realizemos o recomeço do ciclo, nunca mais haverá paz até a nossa morte. No momento certo, vocês encontrarão como fazer, e ele os guiará no seu novo recomeço e de nossas espécies.<br/>
        &emsp;&emsp;<span class="first-letter">T</span>udo agora está mais confuso, eu compreendo. Não desistam de ouvir, pois isso é crucial...<br/><br/>
        </p>
        <p>
        “Na dança eterna do ciclo, o recomeço não simboliza o verdadeiro fim.
        Ao finalizar, emerge a oportunidade de recomeçar;
        A cada volta nesse ciclo contínuo, novos destinos podem entrelaçar-se;
        Em cada caminho recém-trilhado, uma renovação autêntica para tentarmos novamente.
        O ciclo da vida e da morte não são opostos, mas sim elos de uma mesma corrente;
        A luz e as trevas, longe de serem inimigas, formam as nuances de nossa realidade.
        Enfim, é no recomeço que encontramos a perpetuação de nossa existência.”
        </p>
        <br/><br/><br/>

        <h1>CAPÍTULO 03</h1>
        <h2>QUEM SERÁ CAPAZ DE RECOMEÇAR?</h2>

        <p>
        &emsp;&emsp;<span class="first-letter">A</span>h, tantas vezes me questiono sobre o porquê de permitirmos que tragédias desabem sobre os mortais. Nós, divindades, encontramos certo deleite ao ouvir os lamentos das criaturas, clamando por auxílio, dispostos a oferecer o que não possuem em troca de um suporte que, para nós, seria insignificante. Contudo, é essencial compreender algo: nosso poder divino, toda a nossa força, emanam da fé que os devotos depositam em nossa divindade. Quando somos esquecidos ou negligenciados, nossa potência se dissipa. Curioso, não é? Mesmo que os devotos não percebam, suas celebrações, por vezes simples caprichos culturais, inadvertidamente fortalecem deuses, como na troca de presentes durante um feriado ao final de um ano, por exemplo.
        <br/>
        &emsp;&emsp;<span class="first-letter">N</span>ão possuímos controle absoluto; não podemos interferir no livre arbítrio dos habitantes - pelo que dizem, tampouco nas escolhas de nossos familiares divinos - também não precisa acreditar nisso. Um singelo ato pode desencadear uma cascata de efeitos, comprometendo nossa energia vital conquistada com tanto esforço por meio das adorações e acarretando consequências no conselho divino. Os deuses ancestrais mesmo não se envolvem, mas nós não somos como eles, a fonte de poder deles é inesgotável, nós precisamos lutar pela nossa.
        <br/>
        &emsp;&emsp;<span class="first-letter">N</span>o vasto cenário das dimensões divinas, a ordem é frequentemente dividida em dois ou até mesmo três reinos, variando conforme seu tamanho. Cada um desses reinos ostenta suas próprias normas de convivência, grupos distintos, exércitos exclusivos, bênçãos divinas específicas, minérios singulares, culinárias distintivas, enfim, cada fragmento da criação divina exibe sua singularidade. Até mesmo o processo de eleição dos soberanos desses impérios é esculpido pela evolução única de cada um. É comum que desenvolvamos uma afeição por um dos reinos, embora tal predileção seja extremamente subjetiva e passageira. Por vezes, somos mais generosos em nossas oferendas a um determinado reino, ocasionalmente erguemos altares e templos em sua honra - isso nos traz satisfação. Espera-se que o deus que mais se manifesta no reino seja venerado e adorado por seus habitantes, contudo, essa devoção nem sempre se realiza conforme o esperado. Em ocasiões distintas, testemunhamos reinos onde os habitantes optavam por cultuar outros deuses, muitas vezes movidos por imaturidade ou mesmo pela intenção de minar a fé alheia.
        <br/>
        &emsp;&emsp;<span class="first-letter">A</span>lguns de nós raramente são cultuados, mas encontramos maneiras alternativas de sobreviver. A adoração não se manifesta apenas em orações, oferendas ou rituais. Muitas vezes, ela surge de formas inesperadas, como atitudes que refletem a esfera de atuação de um deus. A deusa do amor, dos prazeres carnais, patrona das aves e dos perfumes, também conhecida como deusa das rosas e responsável pela primavera, Milodrye, por exemplo, incita o desejo carnal das pessoas. Quando ela consegue, sem interferência direta, provocar um profundo amor entre um casal em relações íntimas, quando induz um desejo intenso que desencadeia a desordem em um casamento puramente pelo apetite e vontade sexual, ou até mesmo quando instiga a promoção de uma orgia em uma casa de banho, sua vitalidade se renova, e ela nem precisa participar da atividade para se fortalecer ou ser adorada.
        <br/>
        &emsp;&emsp;<span class="first-letter">H</span>á relatos sobre o deus Morbius, patrono dos cavalos, deus da beleza incontestável e do reflexo, deus da auto estima e da graciosidade. Alguns o encontravam como um Djinni, em outras palavras, um gênio mencionado como Morbius. Embora os registros históricos mostrem que ele nunca foi capaz de criar, sempre realizou os desejos de seus súditos, também era muito cultuado quando as pessoas demonstraram inveja sobre a beleza de outra, ou queriam ser tão belos quanto outros. Consegue concretizar desejos obscuros, caros e até mesmo impossíveis, atraindo, porém, a inveja dos súditos de outros deuses. Boatos circulam de que os adoradores de Morbius vivem menos, são aprisionados em sua lâmpada. Esses desejos, de certa forma, fortalecem o deus da beleza.
        <br/>
        &emsp;&emsp;<span class="first-letter">K</span>hefos ostentava a titulação de Deus da abundante colheita, da culinária refinada e do paladar requintado, do vinho exímio e das festividades, além de ser o patrono dos bovinos e suínos. Este deus se destacava pela singularidade de sua aparência em relação aos padrões sociais convencionais, e suas oferendas consistiam sempre em alimentos de qualidade e sabor inigualável. Renomado por sua predileção em trocar favores por banquetes sumptuosos, por vezes ocorreram incidentes em que devotos, após o cumprimento das solicitações de Khefos, falharam em ofertar-lhe os devidos festins. Em tais circunstâncias, o deus utilizou todos os bens e riquezas desses fiéis como se fossem iguarias, incluindo, por vezes, seus próprios entes queridos.
        <br/>
        &emsp;&emsp;<span class="first-letter">W</span>ahdarr é reverenciado como o Deus dos sonhos, do repouso e do descanso, sendo também conhecido como o mensageiro celestial das nuvens. Ele personifica o conforto e a serenidade, tendo como patronos os coalas, roedores e preguiças. Além disso, está intrinsecamente ligado aos anseios humanos, possuindo a capacidade de discernir os mais profundos desejos por meio dos sonhos que permeiam uma noite de sono tranquila. Permitir que os sonhos se manifestem, mesmo que possam assumir a forma de pesadelos, e compartilhá-los com os próximos tornou-se a forma mais comum de adoração a Wahdarr. Geralmente, as pessoas reverenciam o deus do sono antes de se deitarem, suplicando por sonhos serenos e pacíficos.
        <br/>
        &emsp;&emsp;<span class="first-letter">H</span>axy é reverenciado como o Deus da beligerância e do conflito, das artes estratégicas de guerra e da aplicação da tortura, sendo o arauto do derramamento de sangue e da aversão. Ele é o padroeiro dos morcegos e dos bodes, personificando a fúria. Suas oferendas exigem usualmente promessas de batalhas e, geralmente, ele não concede atenção àqueles desprovidos de influência no reino. Há uma forte correlação entre Haxy e o Deus do submundo, frequentemente sendo adorados em conjunto. Causar repulsa nas pessoas torna-se uma forma indireta de adoração a este deus.
        <br/>
        &emsp;&emsp;<span class="first-letter">A</span>latéia é reverenciada como a divindade dos poderosos, um ser venerado por aqueles que exibem um orgulho desmedido por seus feitos. Conhecida também como a deusa lunar, ela personifica o brilho noturno, a obscuridade e o temor, além de ser associada à desonestidade e à vergonha. Desde tempos imemoriais, Alatéia foi vinculada a animais de pelagem escura, como corvos, cervos de pelagem negra, panteras, raposas negras e serpentes. Alatéia não demanda oferendas, mas apenas presta auxílio àqueles que compartilham de seus princípios de poder. Embora se sugira que possa ter desempenhado um papel na criação do submundo, poucos detalhes sobre essa narrativa perduram. Segundo a tradição, ela reinará sobre os mortos, conferindo poder àqueles que transitarem para seu reino após a morte, onde apenas os indivíduos fortes e poderosos serão considerados dignos de sua atenção.
        <br/>
        &emsp;&emsp;<span class="first-letter">N</span>yara é reconhecido como a divindade do ouro e das riquezas, o patrono dos belos presentes e da honestidade, além de personificar da prosperidade e a fortuna. Desde tempos imemoriais, tem sido associado aos felinos, principalmente aos gatos, que o reverenciam como seu protetor. Sua essência reflete o apego ao material, e as oferendas destinadas a ele devem consistir em objetos tangíveis e de valor substancial. Nyara é conhecido por seu discernimento aguçado em relação ao valor, avaliando meticulosamente a condição e a essência de seus devotos antes de considerar qualquer oferta como verdadeiramente significativa. Narrativas lendárias destacam que Nyara uma vez considerou um simples boneco de madeira de uma criança como algo de grande valor, pois representava tudo o que ela possuía, enquanto ignorou um baú repleto de moedas douradas ofertado por um avarento que detinha riquezas inestimáveis.
        </p>


        `
    },
    {
        img: "aetherya_bg3.jpg",
        title: "Aetherya",
        text: `
          
        <h1>REINOS</h1>
        <h2>CAPÍTULO 01 - AETHERYA</h2>

        <p>
            &emsp;&emsp;<span class="first-letter">N</span>um reino resplandecente e incorruptível, os Aetherianos carregam consigo a herança divina da preguiça e a benção da água, conferindo-lhes uma personalidade mais tranquila e com menos conflitos, frequentemente mal interpretada pelos demais habitantes como covardia. Neste reino, a própria natureza, em sua generosidade, concede vida, muitas vezes dispensando a necessidade de progenitores para o nascimento dos Aetherianos. Ao longo dos anos, sua existência tornou-se inextricavelmente entrelaçada à responsabilidade de preservar os recursos da terra, transformando os descendentes de Aetherya em dedicados guardiões da natureza e suas criações.<br/>
            &emsp;&emsp;<span class="first-letter">O</span> patrono supremo dessas criaturas, denominado Emórius, é reverenciado como o deus da água e o criador da vida. Sua entidade muitas vezes é identificada com os próprios oceanos, sendo estes frequentemente escolhidos como locais sagrados para a adoração do grandioso Emórius. A singularidade da criação Aetheriana é notável, sendo o reino de Aetherya o primeiro a erguer estruturas e dar vida a criaturas sem depender de controle direto dos deuses. Seus irmãos, igualmente invejosos, deram início à criação dos outros reinos, entretanto, Emórius estava decidido a fazer dos Aetherianos os cidadãos mais poderosos e organizados que o mundo de Yiridessa testemunharia.<br/>
            &emsp;&emsp;<span class="first-letter">A</span>s criações de Emórius eram tão prepotentes e soberbas quanto o próprio deus dos mares. O início do continente foi marcado por um período de dor e sofrimento, em busca da perfeição. As crianças que não exibiam talentos excepcionais eram relegadas ao trabalho para aquelas mais poderosas. As famílias de baixo poder aquisitivo enfrentavam uma sentença de morte lenta por meio de trabalho escravo e escassez de alimentos. Contudo, as proles de Emórius, embora egoístas como o oceano que os gerou, decidiram que tal regime não perduraria quando Milodrye se apaixonou por uma mortal.<br/>
            &emsp;&emsp;<span class="first-letter">O</span>s Aetherianos não eram dotados de caridade ou benevolência, mas eram capazes de mover montanhas quando suas vontades estavam em jogo. Os deuses menores eram impelidos pela adoração, e a única forma de enfraquecer Emórius era cessar a devoção de suas criaturas. Milodrye, estrategicamente, persuadiu sua irmã Alatéia a usar sua sedução para atrair a atenção do povo, gradualmente desviando seus adoradores de Emórius. Após algumas horas, os deuses menores foram descobertos. Em resposta, Emórius, alegando traição, submeteu Alatéia a uma tortura brutal até que ela revelasse o verdadeiro motivo por trás da tentativa de subverter seu reinado.<br/>
            &emsp;&emsp;<span class="first-letter">F</span>urioso, Emórius libertou Alatéia e, movido por um ódio ardente, dirigiu-se à amada humana de Milodrye. Em uma sequência de torturas desumanas, humilhações e atos abomináveis, Emórius fez Milodrye assistir impotente à agonia da mortal. Quando a humana finalmente sucumbiu à morte, Emórius revelou que Alatéia havia traído seus segredos após semanas de tormento. Passaram-se meses, e os planos dos deuses menores continuaram em execução, mesmo que Milodrye nutrisse um profundo ressentimento por Alatéia.<br/>
            &emsp;&emsp;<span class="first-letter">E</span>m um momento de fragilidade, Emórius enfraqueceu, o que permitiu que seus próprios filhos o esquartejassem, distribuindo seus pedaços por todo o universo de Yiridessa, assegurando que nenhum fragmento tocasse o oceano. Sob a liderança de Alatéia e Milodrye, os Aetherianos passaram a viver em paz, em um reino que, embora respeitasse a monarquia estabelecida no primeiro reinado, promulgava leis de igualdade.<br/>
            &emsp;&emsp;<span class="first-letter">A</span> reprodução dos Aetherianos pode seguir caminhos tradicionais, mas a mera interação do pólen de uma flor nas águas cristalinas do lago de Atherya pode dar origem a um novo defensor dos recursos naturais, conhecido como "Filho da Luz". A essência do dilema reside na interpretação equivocada de seus princípios: os Aetherianos não se opõem ao uso de recursos naturais, mas sim à sua exploração desenfreada e desnecessária.<br/>
            &emsp;&emsp;<span class="first-letter">D</span>entro dessa espécie, as características mutáveis do DNA são influenciadas tanto pelos pais quanto pela necessidade da natureza. Os Altos Elfos, defensores da luz solar, destacam-se pela beleza natural, rostos delicados e reações hormonais sutis. Responsáveis por manter a pureza no reino, eles administram julgamentos justos e preservam o castelo real. Enquanto isso, os Drow, encarregados do brilho lunar, compartilham semelhanças com os Altos Elfos, exibindo pele pálida que reflete a luz lunar, cabelos brancos e sobrancelhas marcantes, desempenhando um papel vital na preservação da harmonia no reino.<br/><br/>
        </p>

        `
    },
   
]